CREATE OR REPLACE FUNCTION bytea_import(p_path text, p_result out bytea)
LANGUAGE plpgsql AS $$
DECLARE
l_oid oid;
BEGIN
SELECT lo_import(p_path) INTO l_oid;
SELECT lo_get(l_oid) INTO p_result;
PERFORM lo_unlink(l_oid);
END;$$;

CREATE TABLE public.Cards
(
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	"Image" bytea NOT NULL,
    "Name" character varying(50) COLLATE pg_catalog."default",
    "Card set" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Cards_pkey" PRIMARY KEY ("id")
);

INSERT INTO Cards ("id", "Image", "Name", "Card set")
VALUES(001, bytea_import('C:\magic\core21\en_wp7nVUSafb.png'), 'Daybreak Charger', 'Core Set 21'),
		(002, bytea_import('C:\magic\ikoria\en_PjLvkLzdSQ.png'), 'Mothra, Supersonic Queen', 'Ikoria'),
		(003, bytea_import('C:\magic\kaldheim\ru_sUrnxuYUqY.png'), 'Финн, Клыконосец', 'Калдхайм'),
		(004, bytea_import('C:\magic\strixhaven\ru_upAklHKLFj.png'), 'Искривление Времени', 'Стриксхейвен'),
		(005, bytea_import('C:\magic\ikoria\en_wgwxf71dPn.png'), 'Tentative Connection', 'Ikoria'),
		(006, bytea_import('C:\magic\kaldheim\ru_gFjNFLjPld.png'), 'Карфеллский Псарь', 'Калдхайм'),
		(007, bytea_import('C:\magic\kaldheim\ru_IDOYVhbin1.png'), 'Стражник Зала Богов', 'Калдхайм'),
		(008, bytea_import('C:\magic\ikoria\en_T4HOiGr7fx.png'), 'Avian Oddity', 'Ikoria'),
		(009, bytea_import('C:\magic\kaldheim\ru_ULWbffIYbH.png'), 'Ледошкурый Тролль', 'Калдхайм'),
		(010, bytea_import('C:\magic\kaldheim\ru_wwAXaaL4oW.png'), 'Дракон Золотого Моста', 'Калдхайм'),
		(011, bytea_import('C:\magic\core21\c.png'), 'Turret Ogre', 'Core Set 21'),
		(012, bytea_import('C:\magic\strixhaven\ru_dLmhxxX9Xi.png'), 'Удар Молнии', 'Стриксхейвен'),
		(013, bytea_import('C:\magic\core21\en_ztfyCQysLg.png'), 'Island', 'Core Set 21'),
		(014, bytea_import('C:\magic\ikoria\en_U5Qg8aJtjf.png'), 'Suffocating Fumes', 'Ikoria'),
		(015, bytea_import('C:\magic\strixhaven\ru_VoOTzlGkF7.png'), 'Выбор', 'Стриксхейвен'),
		(016, bytea_import('C:\magic\core21\en_54KptLxJ1h.png'), 'Grim Tutor', 'Core Set 21'),
		(017, bytea_import('C:\magic\strixhaven\ru_86MtC0M2SH.png'), 'Насилие', 'Стриксхейвен'),
		(018, bytea_import('C:\magic\core21\en_fU3MEi77xk.png'), 'Feline Sovereign', 'Core Set 21'),
		(019, bytea_import('C:\magic\ikoria\en_2bFeo99omt.png'), 'Lead the Stampede', 'Ikoria'),
		(020, bytea_import('C:\magic\strixhaven\ru_GvGcna4vRF.png'), 'Мечи на Орала', 'Стриксхейвен');